sudo: required

services:
  - docker

before_install:
  - docker build -t kryz81/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kryz81/react-test npm test

after_success:
  - docker build -t kryz81/multi-client ./client
  - docker build -t kryz81/multi-nginx ./nginx
  - docker build -t kryz81/multi-server ./server
  - docker build -t kryz81/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kryz81/multi-client
  - docker push kryz81/multi-nginx
  - docker push kryz81/multi-server
  - docker push kryz81/multi-worker