version: "3"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: nginx
    ports:
      - "8080:80"
    depends_on:
      - api
      - client

  api:
    build:
      dockerfile: Dockerfile.dev
      context: server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DATABASE: postgres
      PG_HOST: postgres
      PG_PORT: 5432

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - /app/node_modules
      - ./worker:/app

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
